from typing import Dict, List

from classes import profiles

"""
Initial Setup

Do not edit this file (base.py) directly. Instead copy
its contents into custom.py and edit that file.

You can update the arguments to StrategyProfile to fit
your specifications. An example is included below.

This should be the primary mechanism by which you modify
the market making strategy. Editing other files may lead to
unpredictable results.
"""


def get_strategies() -> Dict[str, profiles.StrategyProfile]:
    strategies: Dict[str, profiles.StrategyProfile] = {}

    # Default profile
    default_markets: List[profiles.MarketProfile] = []
    strategies["default"] = profiles.StrategyProfile(
        profiles.Environment.DEMO, default_markets
    )

    return strategies
