from typing import Dict, List

from classes import profiles

"""
Initial Setup

Do not edit this file (base.py) directly. Instead copy
its contents into custom.py and edit that file.

You can update the arguments to StrategyProfile to fit
your specifications. An example is included below.

This should be the primary mechanism by which you modify
the market making strategy. Editing other files may lead to
unpredictable results.
"""


def get_strategies() -> Dict[str, profiles.StrategyProfile]:
    strategies: Dict[str, profiles.StrategyProfile] = {}

    # Default profile
    default_markets: List[profiles.MarketProfile] = [
        """
        MarketProfile(
            market_ticker="",

            # The amount of liquidity you'd like to provide
            # at each given moment, per side.
            instant_liquidity_cents=10000,

            # The maximum exposure you're willing to take from
            # your position in a market.
            max_exposure_cents=20000,

            # The amount of ticks between the yes and no liquidity
            # you provide. Only odd numbers are currently supported.
            spread=3,

            # The amount of ticks on which you provide
            # liquidity on each side.
            depth=5,

            # The price band in which you're willing to provide liquidity.
            # No orders will be placed on either side outside this band.
            max_yes_price=67,
            min_yes_price=10,

            # The datetime at which you'd like your resting orders to
            # automatically clear.
            clear_time=None,

            # The manner you'd like to distribute your liquidity across
            # the 'depth' of ticks. Supported strategies:
            # LINEAR: Resting orders of equal size are placed at each tick.
            distribution=Distribution.LINEAR,
        )
        """
    ]
    strategies["default"] = profiles.StrategyProfile(
        profiles.Environment.DEMO, default_markets
    )

    return strategies
